### PR TITLE
[nicknamer] Handle cases where nickname >= 32 characters

### PR DESCRIPTION
**Pull request by kablekompany**

### CODE REVIEW

**Comment by Dav-Git** [comment]
Could you extract this unit a function and add the check to all commands that have user input?

**Comment by kablekompany** [comment]
Certainly. I'll push some changes to this branch

**Comment by kablekompany** [comment]
add decorator to check the bot has initial permissions to edit the nickname, as well as internal check for a nickname under 32 characters for each function requiring that input from user.

**Comment by kablekompany** [comment]
ready for review

**Review by Dav-Git — APPROVED** [review]

**Comment by Dav-Git** [comment]
Thanks for your contribution

**Comment by kablekompany** [comment]
Pleasure

**Pull request merged**
