### PR TITLE
[Ticketer] Small changes in the code

### PR DESCRIPTION
**Pull request by kreus7**
Why use `{ctx.author.name}#{ctx.author.discriminator}` when you can use `{ctx.author}`? Just checking whether there was a reason behind this - I just thought I'd make this PR to clean things up a little.

### CODE REVIEW

**Comment by Dav-Git** [comment]
Hehe, the reason was my lack of knowledge of the string method for user objects and my lack of motivation to find such occurances in my code :) Thanks for the PR

**Comment by kreus7** [comment]
No problem. I don't have much time this week to fix the styles, so I'll come round to it next week unless you're willing to fix that all up this week.

**Comment by Dav-Git** [comment]
Works for me :)

**Comment by kreus7** [comment]
Black keeps failing on me 😂

**Comment by Dav-Git** [comment]
No worries, I'll check Monday :)

**Comment by kreus7** [comment]
SGTM 👍🏾

**Review by Dav-Git — APPROVED** [review]
Thanks for the PR again

**Pull request merged**
