### PR TITLE
Update Ticketer for easier categories.

### PR DESCRIPTION
**Pull request by CraziiAce**
I've never really made a PR before, but this is a simple fix for an inconvenience.

### CODE REVIEW

**Comment by CraziiAce** [comment]
Sorry, I'm kind of confused. As I said, I've never made a PR before, and I don't know how to format code. However, I invited you as a contributor on my fork.

**Comment by Dav-Git** [comment]
Awesome, I'll take a look when I have time in the next few days :) Thanks for helping out :)

**Comment by CraziiAce** [comment]
Great!

**Comment by Dav-Git** [comment]
Hm, for some reason the Style checks don't like us. I'll merge anyways. Thanks for the PR.

**Review by Dav-Git — APPROVED** [review]

**Pull request merged**
